spring:
  application:
    name: simon-java-mp
server:
  port: 9999

mp:
  token: flowstone
  appId: wxb1c4473c91444496
  appSecret: f8d15ca6d1deab4aa1cffab40cfd025a
base:
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={APPID}&secret={APPSECRET}
  callbackIpUrl: https://api.weixin.qq.com/cgi-bin/getcallbackip?access_token={ACCESS_TOKEN}
  apiIpUrl: https://api.weixin.qq.com/cgi-bin/get_api_domain_ip?access_token={ACCESS_TOKEN}
talk:
  serviceCenter:
    add: https://api.weixin.qq.com/customservice/kfaccount/add?access_token=
    modify: https://api.weixin.qq.com/customservice/kfaccount/update?access_token=
    remove: https://api.weixin.qq.com/customservice/kfaccount/del?access_token=
    list: https://api.weixin.qq.com/cgi-bin/customservice/getkflist?access_token=
    sendMessage: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=
  batchSend:
    uploadImg: https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=
    uploadnews: https://api.weixin.qq.com/cgi-bin/media/uploadnews?access_token={ACCESS_TOKEN}
    sendAllToTag: https://api.weixin.qq.com/cgi-bin/message/mass/sendall?access_token={ACCESS_TOKEN}
    sendOpenId: https://api.weixin.qq.com/cgi-bin/message/mass/send?access_token={ACCESS_TOKEN}
    uploadVideo: https://api.weixin.qq.com/cgi-bin/media/uploadvideo?access_token={ACCESS_TOKEN}
    delete: https://api.weixin.qq.com/cgi-bin/message/mass/delete?access_token={ACCESS_TOKEN}
    preview: https://api.weixin.qq.com/cgi-bin/message/mass/preview?access_token={ACCESS_TOKEN}
    getSendStatus: https://api.weixin.qq.com/cgi-bin/message/mass/get?access_token={ACCESS_TOKEN}
    getSendSpeed: https://api.weixin.qq.com/cgi-bin/message/mass/speed/get?access_token={ACCESS_TOKEN}
    setSendSpeed:  https://api.weixin.qq.com/cgi-bin/message/mass/speed/set?access_token={ACCESS_TOKEN}
  media:
    upload: https://api.weixin.qq.com/cgi-bin/media/upload?access_token=
    list: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token={ACCESS_TOKEN}
  template:
    send: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={ACCESS_TOKEN}
  userTag:
    create: https://api.weixin.qq.com/cgi-bin/tags/create?access_token={ACCESS_TOKEN}
    get: https://api.weixin.qq.com/cgi-bin/tags/get?access_token={ACCESS_TOKEN}
    update: https://api.weixin.qq.com/cgi-bin/tags/update?access_token={ACCESS_TOKEN}
    delete: https://api.weixin.qq.com/cgi-bin/tags/delete?access_token={ACCESS_TOKEN}