spring:
  application:
    name: simon-java-mp
server:
  port: 9999

mp:
  token: flowstone
  appId: wxb1c4473c91444496
  appSecret: f8d15ca6d1deab4aa1cffab40cfd025a
base:
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={APPID}&secret={APPSECRET}
  callbackIpUrl: https://api.weixin.qq.com/cgi-bin/getcallbackip?access_token={ACCESS_TOKEN}
  apiIpUrl: https://api.weixin.qq.com/cgi-bin/get_api_domain_ip?access_token={ACCESS_TOKEN}
talk:
  serviceCenter:
    add: https://api.weixin.qq.com/customservice/kfaccount/add?access_token=
    modify: https://api.weixin.qq.com/customservice/kfaccount/update?access_token=
    remove: https://api.weixin.qq.com/customservice/kfaccount/del?access_token=
    list: https://api.weixin.qq.com/cgi-bin/customservice/getkflist?access_token=
    sendMessage: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token=